平日課題2 Rubyに関する課題
masahiro647564/camp_weekday_task2 pull request #2
Opened 2019-03-04 15:24 UTC by masahiro647564

以下の課題をやりました｡
exercise02-1.rb
exercise02-2.rb
exercise02-3.rb
exercise02-4.rb
exercise02-5.rb
レビューお願いします!!

2019-03-05 11:33 UTC, tassssra requested changes
> close #2

issueを見ると、**平日課題2 : Rubyに関する課題(2) 修正 #3**となっているので、
`close #2`→`close #3`ではないでしょうか？
違ってたらすみません！

2019-03-05 11:33 UTC, tassssra commented on animal.rb
> +# Catクラスの追加(Animalクラスの継承)
コメント付与いいですね!:smile:

2019-03-05 11:58 UTC, tassssra requested changes

2019-03-05 11:58 UTC, tassssra commented on car.rb
> -    @load_weight
`attr_reader :load_weight`があるのでこちらは削除したんですね、ナイスです！

2019-03-05 11:58 UTC, tassssra commented on car.rb
> +    super(name, color)
`super`への変更いいですね！

2019-03-05 11:58 UTC, tassssra commented on car.rb
> +      puts "乗車できません。この車の最大乗車人数は4人です。"
`@passengers == MAX_PASSENGERS`→`@passengers >= MAX_PASSENGERS`
この変更はいいですね、等しい時ではなく`以上`の処理になりましたね！

`"乗車できません。この車の最大乗車人数は4人です。"`
この文字列の`4`の部分を定数MAX_PASSENGERSで式展開すると、より変更に強いコードになると思います！
↓
`"乗車できません。この車の最大乗車人数は#{MAX_PASSENGERS}人です。"`

2019-03-05 14:35 UTC, masahiro647564 commented
レビューチェックありがとうございます!
issueなんですが､最初に作ったissueをclosedにしてしまい､また二個目を作ったんですが､どうやら複雑になってしまったようですね｡すいません

2019-03-06 02:31 UTC, tassssra commented
> レビューにされて気づきました!
> 機能改善しました!

修正ありがとうございます！
さらに変更に強いコードになりましたね:smile:

2019-03-06 02:50 UTC, tassssra approved these changes
> レビューチェックありがとうございます!
> issueなんですが､最初に作ったissueをclosedにしてしまい､また二個目を作ったんですが､どうやら複雑になってしまったようですね｡すいません

`close #2`→`close #3`でPRのマージとissueのクローズが紐付けられましたね:smile:

2019-03-06 02:50 UTC, tassssra commented on car.rb
> -    print "Carクラスのクラス変数@@countは#{@@count}です。"
`print`削除いいですね:thumbsup:

2019-03-06 02:50 UTC, tassssra commented on car.rb
> +  def initialize(name, color, load_weight = 500)
スペース挿入ナイスです:clap:
読みやすくなりました:sunny:

2019-03-06 03:28 UTC, tassssra commented
**LGTM!** 👍

もうメンターレビュー依頼しても大丈夫そうですね:fire:

ただ、
- 〆切が15日でまだ日がある
- 一度提出すると取り返しがつかない
- あとは提出するだけ

ですので出す前に水村さんご自身で**動作チェック**、**コードの最終確認**をしてから提出すると、より6点取れる可能性が高まるかと思います:smile:

2019-03-06 03:33 UTC, masahiro647564 commented
レビューありがとうございます!
もう一回自分で確認作業をしてみます!

2019-03-11 01:48 UTC, koooosuke reviewed
LGTMです！1点だけコメントしました！
確認後セルフマージしちゃって下さい！！！

2019-03-11 01:48 UTC, koooosuke commented on car.rb
> +
個人的に、ここの空白はなくてもいいかなと思いました！

2019-03-14 09:45 UTC, masahiro647564 commented on car.rb
> +
ご指摘ありがとうございます!

2019-03-14 09:45 UTC, merged